# Generated by Django 4.2.5 on 2024-08-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_order'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermeta',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordermeta',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='ordermeta',
            name='product_inv',
        ),
        migrations.AddField(
            model_name='order',
            name='order_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='dashboard.ordermeta'),
        ),
        migrations.AddField(
            model_name='ordermeta',
            name='product_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_meta_product_inventories', to='inventory.productinventory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordermeta',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_meta_customers', to='inventory.customer'),
        ),
    ]
