# Generated by Django 4.2.5 on 2024-08-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_order'),
        ('dashboard', '0002_remove_ordermeta_order_remove_ordermeta_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_meta',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_meta_customers', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='item_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_meta_product_inventories', to='inventory.productinventory'),
        ),
        migrations.DeleteModel(
            name='OrderMeta',
        ),
    ]
