# Generated by Django 4.2.5 on 2024-08-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_alter_productinventory_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='format: required, default-default.png', upload_to='images/', verbose_name='product image')),
                ('item', models.CharField(max_length=100)),
                ('total_price', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer'], name='inventory_o_custome_1b5951_idx'), models.Index(fields=['created_at'], name='inventory_o_created_60ea1c_idx')],
            },
        ),
    ]
