# Generated by Django 4.2.5 on 2024-08-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_zip_customer_zip_code_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
